x=int(input('Digite um número para ver sua tabuada:'))
a=x*1
b=x*2
c=x*3
d=x*4
e=x*5
f=x*6
g=x*7
h=x*8
i=x*9
j=x*10
print(f'{x} x 1 = {a2}')
print(f'{x} x 2 = {b}')
print(f'{x} x 3 = {c}')
print(f'{x} x 4 = {d}')
print(f'{x} x 5 = {e}')
print(f'{x} x 6 = {f}')
print(f'{x} x 7 = {g}')
print(f'{x} x 8 = {h}')
print(f'{x} x 9 = {i}')
print(f'{x} x 10 = {j}')
